version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: service docker status
      - run: |
          cd ~
          git clone https://github.com/OlegGorj/nginx-docker-minimal.git
          cd nginx-docker-minimal
      - run: |
          docker build .
