version: 2
jobs:
  build:
    docker:
      - image: ubuntu:xenial
    steps:
      - run: apt-get update
      - run: apt-get -y install build-essential
      - run: apt-get -y install curl
      - run: apt-get -y install unzip
      - run: apt-get -y install git-all
      - run:
          command: |
            curl -fsSL https://download.docker.com/linux/ubuntu/gpg | apt-key add -
            add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
            apt-cache policy docker-ce
            apt-get install -y docker-ce
            echo "INFO: `date`: ------------------Docker package installation complete--------------------------"
      - run:
          command: |
            cd ~
            git clone https://github.com/OlegGorj/nginx-docker-minimal.git
            cd nginx-docker-minimal
            docker build .
